'use strict';

const registry = require('../shared/js/pm-registry.js');
const Feedback = require('../modules/progress-mode/feedback.js');
const { CONCEPT_SCOPED_MODULE_IDS, questionConceptValues } = require('./concept-catalogue');

const MS_PER_DAY = 24 * 60 * 60 * 1000;
// Recent reviews should outweigh old ones when estimating "is this solid
// right now" — a student who got 3 wrong last month then 5 right this week
// is in a very different place than the reverse. Exponential recency
// weighting (most-recent review weight 1, halving every ~4 reviews back)
// is the simplest version of that idea, without needing a full Bayesian
// update — same "simple over sophisticated, given the data volume" call
// this module's own design doc (the approved plan) makes for Elo over IRT.
const RECENCY_HALF_LIFE_REVIEWS = 4;

function recencyWeight(indexFromMostRecent) {
  return Math.pow(0.5, indexFromMostRecent / RECENCY_HALF_LIFE_REVIEWS);
}

// A signature's `interval_draws` (modules/progress-mode/store.js's
// computeNextSchedule) is generated by the exact same SM-2 recurrence
// (1st correct rep -> 2 [here: reused as 1], 2nd -> 6, then prev*easeFactor)
// a classic day-based SM-2 interval would use — Progress Mode's "draws"
// unit and the standard "days" unit share one recurrence with one seed, so
// reusing the stored interval_draws value AS a day-count is not a
// approximation of a different number, it IS that number, just relabelled
// for a calendar-scheduled consumer (homework/interventions) instead of
// Progress Mode's own in-session draw counter. Documented explicitly here
// since it's the one place this reinterpretation happens.
function daysOverdue(lastReviewedAt, intervalDraws) {
  const elapsedMs = Date.now() - new Date(lastReviewedAt).getTime();
  const elapsedDays = Math.max(0, elapsedMs / MS_PER_DAY);
  const intervalDays = Math.max(1, Number(intervalDraws) || 1);
  return elapsedDays / intervalDays;
}

// Resolves one progress_mode_reviews row's question_signature back to the
// concept value(s) that question belongs to, via the exact same raw-
// question lookup classroom/concept-catalogue.js's own picker uses (only
// meaningful for the 3 concept-scoped modules — a review for any other PM
// source contributes no concept, same "presume a genuine gap, not a bug"
// stance concept-extractors.js documents for unmapped values).
function conceptValuesForReview(row, adaptersById, questionsByModule, projectRoot) {
  const source = registry.get(row.source_key);
  const moduleId = source ? source.moduleId : '';
  if (!CONCEPT_SCOPED_MODULE_IDS.includes(moduleId)) return { moduleId: '', values: [] };

  if (!questionsByModule.has(moduleId)) {
    const adapter = adaptersById.get(moduleId);
    const questions = typeof adapter?.getQuestions === 'function' ? adapter.getQuestions() : [];
    questionsByModule.set(moduleId, new Map(questions.map((question) => [String(question.id || ''), question])));
  }
  const question = questionsByModule.get(moduleId).get(String(row.question_signature || ''));
  if (!question) return { moduleId, values: [] };
  return { moduleId, values: questionConceptValues(moduleId, question, projectRoot) };
}

// Rolls up per-question SM-2 review history (db/progress-mode-reviews-
// schema.sql, already computed by modules/progress-mode/store.js on every
// answer) to concept granularity: for each concept a student has real
// review history for, a recency-weighted mastery percentage and an
// Anki-style "how overdue" ratio (>=1 means due for review by its own
// schedule, regardless of how well it's currently scoring). Pure function —
// `reviewRows` is whatever a caller already fetched from progress_mode_reviews
// (see classroom/class-evidence.js), `adaptersById` a Map<moduleId, adapter>
// (see classroom/adapters.js's createAdapters()).
function computeConceptMastery(reviewRows = [], adaptersById, projectRoot) {
  const questionsByModule = new Map();
  // conceptKey -> { moduleId, value, reviews: [{ correct, completedAt }], latestBySignature: Map }
  const byConcept = new Map();

  reviewRows.forEach((row) => {
    const { moduleId, values } = conceptValuesForReview(row, adaptersById, questionsByModule, projectRoot);
    if (!values.length) return;
    values.forEach((value) => {
      const conceptKey = `${moduleId}::${value}`;
      if (!byConcept.has(conceptKey)) {
        byConcept.set(conceptKey, { moduleId, value, reviews: [], latestBySignature: new Map() });
      }
      const entry = byConcept.get(conceptKey);
      entry.reviews.push({ correct: Boolean(row.correct), completedAt: row.completed_at });
      const signature = String(row.question_signature || '');
      const existingLatest = entry.latestBySignature.get(signature);
      if (!existingLatest || new Date(row.completed_at) > new Date(existingLatest.completed_at)) {
        entry.latestBySignature.set(signature, row);
      }
    });
  });

  const result = {};
  byConcept.forEach((entry, conceptKey) => {
    const phrase = (Feedback.CONCEPT_PHRASES[entry.moduleId] || {})[entry.value];
    if (!phrase) return; // no display copy -> not a real, presentable concept (same gate concept-catalogue.js uses).

    const sortedReviews = entry.reviews.slice().sort((left, right) => new Date(right.completedAt) - new Date(left.completedAt));
    let weightedCorrect = 0;
    let weightedTotal = 0;
    sortedReviews.forEach((review, index) => {
      const weight = recencyWeight(index);
      weightedTotal += weight;
      if (review.correct) weightedCorrect += weight;
    });
    const masteryScore = weightedTotal > 0 ? Math.round((weightedCorrect / weightedTotal) * 100) : 0;

    // Overdue-ness is per DISTINCT QUESTION (each has its own SM-2 clock),
    // not per review event — a concept is "due" if ANY of its constituent
    // questions' own schedule says so, taking the worst (most overdue).
    let dueScore = 0;
    entry.latestBySignature.forEach((row) => {
      dueScore = Math.max(dueScore, daysOverdue(row.completed_at, row.interval_draws));
    });

    const sampleSize = entry.reviews.length;
    const reliable = sampleSize >= Feedback.FEEDBACK_MIN_QUESTIONS;
    result[conceptKey] = {
      moduleId: entry.moduleId,
      value: entry.value,
      label: phrase.label || entry.value,
      masteryScore,
      dueScore: Math.round(dueScore * 100) / 100,
      sampleSize,
      reliable,
      // The two independent reasons a concept is worth targeting: it's
      // genuinely weak (reliable low score) or it's due for spaced review
      // regardless of current score (the actual point of spaced
      // repetition — a "mastered" concept can still decay).
      needsWork: (reliable && masteryScore < Feedback.WEAKNESS_THRESHOLD) || dueScore >= 1
    };
  });
  return result;
}

// Ranks a student's concepts by targeting priority — due-and-weak first,
// then due, then weak, then everything else by dueScore — for callers that
// just want "give me the top N concepts to target" (homework's targeted
// mode, Suggested Intervention) rather than the full per-concept map.
function rankConceptsForTargeting(conceptMastery) {
  return Object.values(conceptMastery)
    .filter((concept) => concept.needsWork)
    .sort((left, right) => {
      const leftWeak = left.reliable && left.masteryScore < Feedback.WEAKNESS_THRESHOLD;
      const rightWeak = right.reliable && right.masteryScore < Feedback.WEAKNESS_THRESHOLD;
      const leftScore = (left.dueScore >= 1 ? 1 : 0) + (leftWeak ? 1 : 0);
      const rightScore = (right.dueScore >= 1 ? 1 : 0) + (rightWeak ? 1 : 0);
      if (leftScore !== rightScore) return rightScore - leftScore;
      return right.dueScore - left.dueScore;
    });
}

module.exports = {
  computeConceptMastery,
  rankConceptsForTargeting
};
